In [ ]:
!pip install meteostat

In [3]:
from meteostat import Stations, Daily
import datetime as dt

In [5]:
stations = Stations()
stations = stations.region('TZ')

print('Stations in Tanzania:', stations.count())

Stations in Tanzania: 27

In [7]:
stations_df = stations.fetch()

In [8]:
stations_df

,name,country,region,wmo,icao,latitude,longitude,elevation,timezone,hourly_start,hourly_end,daily_start,daily_end,monthly_start,monthly_end
id,,,,,,,,,,,,,,,
63729,Bukoba,TZ,KA,63729,HTBU,-1.3333,31.8167,1137.0,Africa/Dar_es_Salaam,1957-01-01,2022-03-30,1950-01-01,2021-12-26,1950-01-01,1989-01-01
63733,Musoma,TZ,MR,63733,HTMU,-1.5000,33.8000,1147.0,Africa/Dar_es_Salaam,1957-01-01,2022-03-30,1950-01-01,2021-12-01,1950-01-01,1989-01-01
63756,Mwanza,TZ,MW,63756,HTMW,-2.4667,32.9167,1139.0,Africa/Dar_es_Salaam,1950-01-08,2022-03-30,1950-01-01,2022-03-28,1950-01-01,2021-01-01
63789,Arusha,TZ,AR,63789,HTAR,-3.3333,36.6167,1387.0,Africa/Dar_es_Salaam,1960-01-11,2022-03-30,1959-02-01,2021-12-01,1959-01-01,1989-01-01
63790,Moshi,TZ,KJ,63790,HTMS,-3.3500,37.3333,854.0,Africa/Dar_es_Salaam,1949-09-09,2022-02-22,1950-01-01,1989-12-31,1950-01-01,1989-01-01
63791,Kilimanjaro Airport,TZ,AR,63791,HTKJ,-3.4167,37.0667,891.0,Africa/Dar_es_Salaam,1970-01-01,2022-03-30,1971-10-01,2022-03-22,1971-01-01,1990-01-01
63801,Kigoma,TZ,KI,63801,HTKA,-4.8833,29.6333,882.0,Africa/Dar_es_Salaam,1957-01-01,2022-03-30,2006-12-13,2021-12-01,NaT,NaT
63816,Same,TZ,KJ,63816,HTSE,-4.0833,37.7167,872.0,Africa/Dar_es_Salaam,1957-01-01,2022-02-22,1950-01-01,1990-02-28,1950-01-01,1990-01-01
63818,Mombo,TZ,TN,63818,HTMO,-4.8833,38.2833,511.0,Africa/Dar_es_Salaam,1958-02-06,2020-11-20,NaT,NaT,NaT,NaT
63832,Tabora Airport,TZ,TB,63832,HTTB,-5.0833,32.8333,1181.0,Africa/Dar_es_Salaam,1949-01-21,2022-03-30,1951-08-01,2022-03-28,1949-01-01,2021-01-01
63844,Tanga,TZ,TN,63844,HTTG,-5.0833,39.0667,39.0,Africa/Dar_es_Salaam,1957-01-01,2022-02-28,NaT,NaT,NaT,NaT
63845,Pemba / Karume Airport,TZ,PS,63845,HTPE,-5.2500,39.8167,25.0,Africa/Dar_es_Salaam,1957-01-01,2022-02-28,NaT,NaT,NaT,NaT
63862,Dodoma,TZ,DO,63862,HTDO,-6.1667,35.7667,1119.0,Africa/Dar_es_Salaam,1950-02-07,2022-03-30,1957-01-01,2022-03-28,1957-01-01,2022-01-01
63866,Morogoro,TZ,MO,63866,HTMG,-6.8333,37.6500,526.0,Africa/Dar_es_Salaam,1957-01-01,2022-03-30,2006-03-12,2021-12-26,NaT,NaT
63870,Zanzibar / Kisauni,TZ,ZU,63870,HTZA,-6.2167,39.2167,15.0,Africa/Dar_es_Salaam,1957-01-01,2022-03-30,1957-01-01,2022-03-28,1957-01-01,2022-01-01
63881,Sumbawanga,TZ,RK,63881,HTSU,-7.9667,31.6333,1923.0,Africa/Dar_es_Salaam,1989-09-02,2022-03-30,2008-06-23,2021-12-26,NaT,NaT
63887,Iringa,TZ,IR,63887,HTIR,-7.6667,35.7500,1426.0,Africa/Dar_es_Salaam,1957-01-01,2022-03-30,1960-01-01,2021-12-01,1960-01-01,1990-01-01
63894,Dar Es Salaam Airport,TZ,DS,63894,HTDA,-6.8667,39.2000,55.0,Africa/Dar_es_Salaam,1950-02-01,2022-03-30,1957-01-01,2022-03-28,1949-01-01,2021-01-01
63900,Lyabusalu,TZ,<NA>,63900,HTSY,-3.5000,33.0000,1168.0,Africa/Dar_es_Salaam,1988-03-24,2022-02-02,NaT,NaT,NaT,NaT
63919,Kilwa Masoko / Kilwamasoko / Kikone,TZ,LN,63919,HTKI,-8.9333,39.5167,18.0,Africa/Dar_es_Salaam,2005-07-01,2022-02-22,NaT,NaT,NaT,NaT
63932,Mbeya,TZ,MB,63932,HTMB,-8.9333,33.4667,1704.0,Africa/Dar_es_Salaam,1949-11-01,2022-03-12,2005-10-06,2013-04-05,NaT,NaT
63962,Songea,TZ,RV,63962,HTSO,-10.6833,35.5833,1067.0,Africa/Dar_es_Salaam,1949-01-21,2022-03-30,1957-01-01,2022-03-28,1949-01-01,2022-01-01
63969,Nachingwea,TZ,LN,63969,HTNA,-10.3500,38.7500,463.0,Africa/Dar_es_Salaam,1957-01-01,2003-06-09,NaT,NaT,NaT,NaT
63971,Mtwara,TZ,MT,63971,HTMT,-10.2667,40.1833,113.0,Africa/Dar_es_Salaam,1957-01-01,2022-03-30,1957-01-01,2022-03-26,1957-01-01,2021-01-01
HTKB0,Kibondo / Irabiro,TZ,KI,<NA>,HTKB,-3.5260,30.6504,1299.0,Africa/Dar_es_Salaam,2020-02-06,2021-12-21,NaT,NaT,NaT,NaT
HTMH0,Makau,TZ,SI,<NA>,HTMH,-3.3711,34.8294,1623.0,Africa/Dar_es_Salaam,2011-07-08,2022-02-28,NaT,NaT,NaT,NaT
HTMP0,Mpanda,TZ,RK,<NA>,HTMP,-6.3500,31.0830,1073.0,Africa/Dar_es_Salaam,2020-02-06,2022-03-30,NaT,NaT,NaT,NaT

In [4]:
start = dt.datetime(2000, 1, 1)
end = dt.datetime(2020, 12, 31)

data = Daily('63729', start, end)
data = data.fetch()

In [5]:
data

            tavg  tmin  tmax  prcp  snow   wdir  wspd  wpgt  pres  tsun
time
2008-05-11  22.3  18.0  26.4   NaN   NaN    NaN   5.3   NaN   NaN   NaN
2008-05-17  22.9  18.8  26.0   NaN   NaN    NaN  11.6   NaN   NaN   NaN
2008-05-19  23.0  19.0  25.1   NaN   NaN    NaN   9.5   NaN   NaN   NaN
2008-05-28  21.8  17.7  25.0   NaN   NaN    NaN   6.3   NaN   NaN   NaN
2008-06-20  21.0  16.9  25.0   NaN   NaN    NaN   5.2   NaN   NaN   NaN
...          ...   ...   ...   ...   ...    ...   ...   ...   ...   ...
2020-12-25  21.0  18.0  25.0   NaN   NaN    6.0   3.9   NaN   NaN   NaN
2020-12-26  21.3  18.0  26.0   NaN   NaN    1.0   4.0   NaN   NaN   NaN
2020-12-27  20.6  17.0  24.0   NaN   NaN  353.0   5.7   NaN   NaN   NaN
2020-12-28  22.7  17.8  28.0   NaN   NaN   22.0   6.0   NaN   NaN   NaN
2020-12-31  20.5  18.0  22.0   NaN   NaN    4.0   2.9   NaN   NaN   NaN

[414 rows x 10 columns]